# This is a basic workflow to help you get started with Actions

name: test download artifact

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      
      # Runs a set of commands using the runners shell
      - name: toop
        run: echo foobar > foo.txt
        
      - uses: actions/upload-artifact@v3
        with:
          name: foob
          path: foo.txt
          
      - uses: actions/download-artifact@v3
        with:
          name: foob
    
      - name: Display structure of downloaded files
        run: ls -R
