# This is a basic workflow to help you get started with Actions

name: test download filmz

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      
      - name: mkdcd
        run: mkdir bin
      - name: seedee
        run: cd bin
      - name: installwget
        run: apt install -Y wget
        
      # Runs a set of commands using the runners shell
      - name: getfilm 1
        run: wget http://d2.o2tv.org/The%20Walking%20Dead%20-%20Dead%20City/Season%2001/The%20Walking%20Dead%20-%20Dead%20City%20-%20S01E01%20HD%20(TvShows4Mobile.Com)%20otv-hjup8.mp4
        
      - name: get film 2
        run: wget http://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip
      - name: back
        run: cd ..
        
      - name: tarthat
        run: tar -cf bin.tar bin
      - name: gzthat
        run: gzip bin.tar
        
      - uses: actions/upload-artifact@v3
        with:
          name: film
          path: bin.tar.gz
