# This is a basic workflow to help you get started with Actions

name: build ghr

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4

      # Runs a single command using the runners shell
      - name: build ghr
        run: go install github.com/tcnksm/ghr@latest
      - name: lsd much?
        run: ls -lth

      # Runs a set of commands using the runners shell
      - name: tarthat
        run: tar -cf binz.tar bin
      - name: gzipthat
        run: gzip binz.tar
        
      - uses: actions/upload-artifact@v3
        with:
          name: ghrb
          path: ghr binz.tar.gz
