# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build ghr

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go install github.com/tcnksm/ghr@latest
      
    - name: download file
      run: wget https://download.manjaro.org/kde/22.1.3/manjaro-kde-22.1.3-230529-linux61.iso
      
    - name: build Splitter
      run: javac Splitter.java
      
    - name: splitt
      run: java Splitter manjaro-kde-22.1.3-230529-linux61.iso
      
    - name: ls dirp
      run: ls -R -lh
      
    - name: gittar
      run: ghr -t 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 -u cassyjay645 -r fishfood v1.1.1 out/
    
      
    
