
name: jserver

on:
  workflow_dispatch:
    inputs:
      url:
        required: true
        description: url
        type: string
      fname:
        required: false
        type: string
        description: filename
        default: 'fname'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build dll
      run: javac dll.java
    - name: wget
      run: java dll ${{ inputs.url }} 'whrx.mp4'
    - name: lsdirp
      run: ls -R
